name: Playwright Tests (Docker)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for building image
        uses: actions/checkout@v4
      # we build the image here. And then we re-fetch it. In reality we would only push the image
      # after a successful test suite has been done
      # but in this case we only want to demo the flow
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t kimmoahola/ec-docker-demo:latest .

      - name: Push Docker image
        run: |
          docker push kimmoahola/ec-docker-demo:latest

      - name: Start Spring Boot app
        run: |
          docker run -d \
            --name app \
            -p 8080:8080 \
            -e BASE_URL=http://localhost:8080 \
            kimmoahola/ec-docker-demo:latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Wait for app
        run: |
          npm install -g wait-on
          wait-on http://localhost:8080 --timeout 60000

      - name: Run Playwright tests inside container
        run: |
          docker exec app ./mvnw test

      - name: Stop container
        if: always()
        run: docker stop app && docker rm app
